name: Server Keep alive
on:
    push:
        branches: [master]

jobs:
    server_restart:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # Congifure git to commit to the Repo    
            - name: Set up Git
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Restart server
              run : |
                mkdir -p backup
                cd backup
                git clone https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/mokshraj/Mine_server.git .git
                cd Mine_server
                git pull
                git commit --allow-empty -m "server-start"
                git push origin master
                
            - name: backup server
              run : |
                cd backup
                cd Mine_server
                # Compress the .git folder
                zip -r git_backup.zip .git
                # Split into 90MB chunks
                split -b 90M git_backup.zip git_backup.zip.part_
                # Remove original zip and .git to save space
                rm -rf git_backup.zip .git
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                git status
                git pull
                git add .
                git status
                git commit --allow-empty -m "server save"
                git status
                git push origin master
                git status
